name: banking_home
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets: 
    - assets/icons/

  fonts:
    - family: Glook
      fonts: 
        - asset: assets/fonts/Gloock-Regular.ttf
    - family: Ubuntu
      fonts: 
        - asset: assets/fonts/Ubuntu-Regular.ttf
